# Generated by Django 2.0.3 on 2018-03-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Client_Contact_Person',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
