# Generated by Django 2.0.3 on 2018-04-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CircleInvite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circleinvite',
            name='CircleInvite_Accepted',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
