# Generated by Django 2.0.3 on 2018-04-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actors',
            old_name='ACTOR_Skin_Color',
            new_name='Actor_Skin_Color',
        ),
    ]
